/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Chalini
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentbtn = new javax.swing.JButton();
        bookbtn = new javax.swing.JButton();
        issuebookbtn = new javax.swing.JButton();
        returnbookbtn = new javax.swing.JButton();
        dvdbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentbtn.setText("Students");
        studentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentbtnActionPerformed(evt);
            }
        });
        getContentPane().add(studentbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, 30));

        bookbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bookbtn.setText("Books");
        bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbtnActionPerformed(evt);
            }
        });
        getContentPane().add(bookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 150, 30));

        issuebookbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        issuebookbtn.setText("Issue Book");
        issuebookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuebookbtnActionPerformed(evt);
            }
        });
        getContentPane().add(issuebookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, 30));

        returnbookbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        returnbookbtn.setText("Return Book");
        returnbookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbookbtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnbookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 150, 30));

        dvdbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dvdbtn.setText("DVD");
        dvdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvdbtnActionPerformed(evt);
            }
        });
        getContentPane().add(dvdbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to Saegis Campus Library.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 610, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image2.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbtnActionPerformed
        book bo = new book();
        bo.setVisible(true);
    }//GEN-LAST:event_bookbtnActionPerformed

    private void returnbookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbookbtnActionPerformed
        returnbook re = new returnbook();
        re.setVisible(true);
    }//GEN-LAST:event_returnbookbtnActionPerformed

    private void studentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentbtnActionPerformed
        student st = new student();
        st.setVisible(true);
        
        
    }//GEN-LAST:event_studentbtnActionPerformed

    private void issuebookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuebookbtnActionPerformed
        issuebook is = new issuebook();
        is.setVisible(true);
        
    }//GEN-LAST:event_issuebookbtnActionPerformed

    private void dvdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvdbtnActionPerformed
        dvd dv = new dvd();
        dv.setVisible(true);
    }//GEN-LAST:event_dvdbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookbtn;
    private javax.swing.JButton dvdbtn;
    private javax.swing.JButton issuebookbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton returnbookbtn;
    private javax.swing.JButton studentbtn;
    // End of variables declaration//GEN-END:variables
}
